version: '3.9'

services:
  java_app:
    container_name: java_app
    image: java-app:1.0.0
    restart: always
    build: .
    ports:
      - 8080:8080
    environment:
       MYSQL_URL: jdbc:mysql://java_db:3306/ecotienda
       MYSQL_USERNAME: root
       MYSQL_PASSWORD: admin
       MP_ACCESS_TOKEN: APP_USR-3209786323129874-092615-e4bdbae746c1335ce5a7632e6bc4a52e-1490810411
    depends_on:
      - java_db
  java_db:
    container_name: java_db
    image: mysql:latest
    volumes:
      - /home/ivan/c15-21-m-java-angular/db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
       MYSQL_DATABASE: ecotienda
       MYSQL_ROOT_PASSWORD: admin