// Generated by https://quicktype.io

export interface DetailResponse {
  id: number;
  nombre: string;
  precio: number;
  stock: number;
  categorias: Categoria[];
  descripcion: string;
  codigo: string;
  imagen: string;
  ratings: Rating[];
}

export interface Categoria {
  id: number;
  nombre: string;
  descripcion: string;
  imagen: string;
}

export interface Rating {
  id: number;
  rating: number;
  comment: string;
  date: string;
  userNombre: null;
  userFirstName: string;
}
