// Generated by https://quicktype.io

export interface ProductsResponse {
  id: number;
  nombre: string;
  precio: number;
  stock: number;
  categorias: Categoria[];
  codigo: string;
  imagen: string;
}

export interface Categoria {
  id: number;
  nombre: string;
  descripcion: string;
}
